### ISSUE TITLE
Jira is not sending from @geek.zone email addresses

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/dns-terraform#1]
### What did you expect?

Jira should send from @geek.zone email addresses

### What actually happened?

Jira is currently sending from an atlassian address. This is potentially due to misconfigured [DMARC records](https://support.atlassian.com/jira-service-management-cloud/docs/manage-dmarc-authentication-for-incoming-emails/).

See also [What are the steps for setting up custom email addresses?](https://support.atlassian.com/organization-administration/docs/what-are-the-steps-for-setting-up-custom-email-addresses/)

### Impact

High

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesgeddes** [comment]
@giulio-giunta and @kbcbals should I move this to the infa repo?

**Comment by kbcbals** [comment]
@jamesgeddes I dont completely understand the issue  but I think its infra issue

**Comment by jamesgeddes** [comment]
Thanks @kbcbals 

As I understand it, we need to update DNS with the required DMARC records. Have updated description with instructions.

Will move to infra as you have suggested.

**Comment by jamesgeddes** [comment]
I have put the required settings into cloudflare (not in terraform at this time, sorry). Jira is now sending email, but from jira@geekzone.atlassian.net. Jira tells me that the DNS has failed, but I have confirmed that our cloudflare is working as expected. I have submitted a support ticket to Atlassian and am awaiting a response.

**Comment by jamesgeddes** [comment]
Jira is working! 🥳 

I neglected to write any terraform as I needed to just get it working, so @VAO11 please continue working on getting our long-lived DNS configuration into terraform.
